README.md, package-lock.json, package.json, scratch.js, src/Lib.purs, src/Ogmios.js, src/Ogmios.purs, src/Types.purs
we now have some functionality to query utxo's using an ogmios backend via websocket.
(resolves https://github.com/Plutonomicon/cardano-browser-tx/issues/5)
next, we must transform inputs to outputs to create our partial tx, then fully balance the tx.
=> Query Ogmios for Utxos at a given address

README.md
adds documentation for a successful setup of the cardano node and ogmios. 
currently this excludes the wallet backend, however that should be added in the near future.
=> docs updates for infra setup

spago.dhall, src/Serialization.js, src/Serialization.purs, src/Types/POSIXTimeRange.purs, src/Types/Transaction.purs, src/Types/UnbalancedTransaction.purs
=> Add UnbalancedTransaction data type

README.md
This applies the addition of CI-integration badges to the readme file; allowing people to click links to reach Hercules and cachix
=> updating readme with ci badges

src/Types/PlutusData.purs
=> Add PlutusData type

src/Deserialization/BigInt.js, src/Deserialization/BigInt.purs, src/Deserialization/PlutusData.js, src/Deserialization/PlutusData.purs, src/Serialization/BigInt.js, src/Serialization/BigInt.purs, test/Deserialization.purs, test/Fixtures.purs
Follow-up for #119, closes #118
=> Add deserialization for PlutusData

README.md, src/Wallet.js, src/Wallet.purs
Came across something that might cause problems soon.
=> Fix unsafe wallet function implementation

src/Types/Value.purs
With the new `mkTokenName`, I think it's now safe to export `adaToken`. In particular, we can relax some conditions on `mkSingletonValue'` and `mkSingletonValue`.
=> Fix to `mkSingletonValue`, `mkSingletonValue'` and `adaToken` now exportable

src/Serialization/WitnessSet.purs, src/Transaction.purs, test/Transaction.purs
Closes #144 
This is very similar to #146
=> Attach redeemer to transaction

src/Aeson.js
Suggested comments improvements.
=> Add additional js code comments.

src/Deserialization/WitnessSet.purs, src/ProtocolParametersAlonzo.purs, src/Serialization.js, src/Serialization.purs, src/Serialization/PlutusData.purs, src/Serialization/Types.purs, src/Serialization/WitnessSet.js, src/Serialization/WitnessSet.purs, src/Transaction.purs, src/Types/Transaction.purs, test/Transaction.purs
Closes #145 
The script witness part is very similar to #146 and #158. This also takes care of setting the script data hash in the tx body
=> Attach scripts and script data hash

spago.dhall, src/Aeson.js, src/Aeson.purs, src/Types/PlutusData.purs, test/Aeson.purs, test/Main.purs
Extending Aeson module to provide needed functionality for jsonwsp workings.
=> Extend Aeson module 

Makefile, examples/nami/Pkh2Pkh.purs, examples/nami/Simple.purs, src/DatumCacheWsp.purs, src/MultiMap.purs, src/QueryM.purs, src/Serialization/Address.purs, src/Types/JsonWsp.purs, test/AffInterface.purs
Previous PR #164 
- All comments from previous (closed) PR are addressed or answered.
- It targets another branch for better diffs. 
- I intend to write AffInterface like tests in another PR to unlock further work now
-  ogmios-datum-cache does not support mapping ids to messages - proposed solution relies on the current server and ws library implementation ('requests' are handled in fifo order and 'responses' order is preserved).
=> Datum Cache WebSocket and API

examples/nami/Pkh2Pkh.purs, src/Serialization/Address.js, src/Serialization/Address.purs, test/Fixtures.purs, test/Serialization/Address.purs
=> NetworkId to ADT enum.

src/Types/Natural.purs
=> Add `Natural` type

src/FromData.purs, src/ToData.purs, src/Types/Rational.purs
=> Add Ratio, Rational

src/QueryM.purs
=> Use correct URL for ogmios-datum-cache websocket API

src/Metadata/Seabug.purs, test/Fixtures.purs, test/Metadata/Seabug.purs, test/UsedTxOuts.purs
It'll be also [needed](https://drive.google.com/file/d/1F7a0lOWKJhEuYZxcK90qN2UN1rVePXRX/view?usp=sharing).
#186
=> Add SeabugMetadataDelta

src/FromData.purs, src/ToData.purs
My earlier work contains a number of mistakes because I didn't compare it with Plutus.
=> Synchronize ToData/FromData instances with Plutus

examples/nami/Pkh2Pkh.purs, examples/nami/Simple.purs, src/BalanceTx.purs, src/Contract/Monad.purs, src/QueryM.purs, src/Types/ScriptLookups.purs, test/AffInterface.purs
=> Always get the `NetworkId` when building and balancing

Makefile, ci.nix, flake-compat.nix, flake.lock, flake.nix
Fixes an issue I noticed this morning with Hercules. Now CI will build all of the flake outputs
=> Use `flake-compat-ci`

node-packages.nix, package-lock.json, package.json, server/src/Api.hs, server/src/Api/Handlers.hs, server/src/Types.hs, server/test/Main.hs, src/Contract/Prim/ByteArray.purs, src/QueryM.purs, src/Seabug/Contract/MarketPlaceBuy.purs, src/Seabug/Token.purs, src/Seabug/Types.purs, src/Types/ByteArray.js, src/Types/ByteArray.purs
=> Add endpoint and client for blake2b hashing

src/Wallet.js
=> Properly re-throw exceptions in submitTxNami

examples/Seabug/Contract/MarketPlaceListNft.purs, examples/Seabug/Token.purs, examples/Seabug/Types.purs, src/Contract/Prelude.purs, src/Helpers.purs
- Moved/added `filterMapWithKeyM` and `filterMapM` to `Contract` API (will make a separeate PR for this commit into `master`)
- Endpoint to list market place NFTs
=> Viet/seabug deployment/list nft

examples/Seabug/Contract/MarketPlaceListNft.purs, examples/Seabug/Types.purs
- Corrected `marketPlaceListNft` checking for `MarketplaceDatum` instead constructor.
- Removed unnecessary `FromData` `ToData` instances of `NftCollection` and `NftData`
=> correct datum from listing nfts

examples/Seabug/Test.purs, examples/Seabug/Token.purs
Attempts to close https://github.com/Plutonomicon/cardano-browser-tx/issues/247
- So far, I've only changed the locking script to match the input.
- Also realised the arguments were being overapplied so had to remove a few to match `applyCode` on the Plutus side
=> Token name and currency symbol mismatch

server/src/Api/Handlers.hs, src/Contract/Transaction.purs, src/QueryM.purs, src/QueryM/Submit.purs, src/Types/JsonWsp.purs, src/Types/Transaction.purs, src/Types/UnbalancedTransaction.purs, test/FinalizeTx.purs
Closes #131. Work done by @klntsky. Replay of #245 since we don't need the test contract from my other branch and depending on the Plutus compiler plugin kills CI
=> Ogmios submit (applies changes from #245)

server/src/Api/Handlers.hs
This should also be cherry-picked to master
=> Use PlutusV1

src/Address.purs, src/BalanceTx.purs, src/Contract/Address.purs, src/Contract/Scripts.purs, src/Scripts.purs, src/TxOutput.purs, src/Types/ScriptLookups.purs, src/Types/UnbalancedTransaction.purs, src/Wallet.js
- Various address helper fixes and lookup changes. The addresses *seem* to align with what they should be now.
- Added network id to transaction body inside balancer.
- Outstanding issue is we can't get the collateral added.
=> Address fixes 

examples/Seabug/Types.purs, src/Types/ScriptLookups.purs
- Strip datums and redeemers after constraint lookups.
- Fix ToData instance of  marketplacedatum
=> fix ToData and strip datum and redeemers

src/Contract/Address.purs, src/Contract/Monad.purs, src/Contract/PlutusData.purs, src/Contract/ScriptLookups.purs, src/Contract/Scripts.purs, src/Contract/Transaction.purs, src/Contract/Utxos.purs, src/Contract/Value.purs, src/Contract/Wallet.purs, src/QueryM.purs, src/Types/ScriptLookups.purs, test/FinalizeTx.purs
Re-play of #261 since CI wouldn't run from the fork. I'm quite happy with @errfrom's solution here, it would have been nice to have when we wrote the Seabug contracts
=> Extensible `ContractConfig` (#261)

src/Metadata/Seabug.purs, src/Metadata/Seabug/Share.purs
=> Fix Seabug `share` range

README.md, examples/Serialization.purs, flake.nix, nix/default.nix, test/FinalizeTx.purs, test/Integration.purs, test/Main.purs, test/Serialization.purs, test/Unit.purs, test/Utils.purs
Closes #328. Now the unit tests will be run by CI to help prevent introducing regressions. I will add a derivation for the integration testing in a separate PR
=> Split tests, add flake `checks` to run tests

src/Contract/Transaction.purs, src/QueryM.purs, src/QueryM/Ogmios.purs
Closes #290. @klntsky I know you were working on this yesterday but the fix is urgently needed by the Cardax team
=> Fix Ogmios submission result parsing

src/Serialization/Hash.purs
> I thought that `scriptHashFromBytes` makes a hash ...
> from bytes
> :slightly_smiling_face:
> (honestly no pun intended :smile:)
wink @bladyjoker
=> Add some documentation

server/src/Api/Handlers.hs, src/QueryM.purs, src/Types/ScriptLookups.purs
- Fix MustPayToPubKeyAddress in lookups
- I increased fees and ex units for Cardax testing. However, we need https://github.com/Plutonomicon/cardano-transaction-lib/issues/174 to resolve this. Happy to remove the fee buffer stuff for merging to master but we need the lookup change above.
=> Fix MustPayToPubKeyAddress in lookups & increase fees

src/QueryM.purs, src/QueryM/DatumCacheWsp.purs
=> Fix `getDatumsByHashes`

README.md, nix/default.nix, package-lock.json, package.json
Fixes issue with `cp -r` expansion (can't use braces with one element)
=> Fix copying `sources` arg to builder

src/Deserialization/Transaction.purs, src/Serialization.js, src/Serialization.purs, src/Serialization/AuxiliaryData.js, src/Serialization/AuxiliaryData.purs, src/Serialization/Types.purs, src/Types/Int.purs, src/Types/Transaction.purs
Closes #354
There are no tests for now (see #355)
=> Add AuxiliaryData and `is_valid` serialization

src/Cardano/Types/Value.purs, src/Types/Rational.purs, src/Types/TokenName.purs
=> Add EncodeJson and DecodeJson for a Rational, TokenName, CurrencySym

src/QueryM/Utxos.purs, src/Wallet.purs
=> Handle missing Nami collateral

Makefile, examples/AlwaysSucceeds.purs, examples/Datums.purs, examples/Pkh2Pkh.purs, src/Contract/Monad.purs
=> Add `AlwaysSucceeds` contract

src/Contract/Chain.purs, src/QueryM.purs, src/QueryM/Ogmios.purs, src/Types/Chain.purs
Closes #372 
Naming is adhoc, feel free to bikeshed on module/function names
=>  Expose `Contract` wrapper around `QueryM.getChainTip`

src/Contract/Monad.purs
=> Fix datum cache connection

flake.nix, server/ctl-server.cabal, server/exe/Main.hs, server/src/Types.hs, server/test/Main.hs
We need to access network id and node socket to calculate exunits.
=> Add CLI options to connect to cardano-node

src/Plutus/Types/CurrencySymbol.purs, src/Serialization/Hash.purs, src/Types/ByteArray.purs, src/Types/Scripts.purs
Needed for purescript-bridge...
Ran the full test suite locally and it passed.
=> Add missing json instances

README.md, flake.nix, nix/default.nix, spago.dhall
=> Add docs package, include `spago docs` and package in readme

packages.dhall, spago-packages.nix, spago.dhall, src/Aeson.purs, src/Contract/Aeson.purs, test/Aeson.purs, test/ArbitraryJson.purs
This adds support for EncodeJson equivalent for Aesons. It will most likely be useful for CTL-bridge things.
=> Add EncodeAeson stuff.

flake.lock, flake.nix
Adds `aarch64-{linux|darwin}` support for Ogmios
=> Upgrade Ogmios to latest master

README.md, package.json, test/Integration.purs, test/Main.purs, test/Unit.purs
=> Improve testing workflow and fix instructions

README.md, flake.nix
=> Runtime config improvements (was #422)

README.md, flake.nix
This change makes it more convenient to change cardano network used by CTL
=> Make cardano-configurations configurable

Makefile, flake.nix
=> Fix postgres port setting. Allow not to bind postgres port at all.

examples/AlwaysMints.purs, examples/Gero.purs, src/BalanceTx.purs, src/Contract/Scripts.purs, src/Contract/Wallet.purs, src/QueryM.purs, src/Wallet.js, src/Wallet.purs
I am still unable to run AlwaysMints with Gero. Neither with `addTxCollateral` nor without it.
Debug info:
```
[DEBUG] 2022-05-31T11:52:44.898Z sending: {"args":{"submit":"84a800818258200b54e1d9ffe153b46b18bfa8c9d2064af98e5e83d4a3c531bd2c28a8bc0703ed00018182583900c4c0d83d066c3c051aaa22a43f06e950f51fbc87efaad639ce0fb2ea46c746c932fa1aa00f2c6112e88e766e58ef641b59b8258f3a8a7ce3821a3b50b362a1581cfda1b6b487bee2e7f64ecf24d24b1224342484c0195ee1b7b943db50a148546865546f6b656e1864021a00055e4f09a1581cfda1b6b487bee2e7f64ecf24d24b1224342484c0195ee1b7b943db50a148546865546f6b656e18640b5820db6c2c1d09962c792776a4f01b41c222109a6e5bd480709579770dd4439a7fcf0d81825820580c2dcdc4529101d423fa664c8ccdd2d2885aa451fc81725cf34d70efb95068000e800f00a300818258204e01eb6350b28da66d21b3cce55c20ade9e933299c1da51c4c97c46f70cb …
```
=> Apply suggestions from code review

src/Cardano/Types/Value.purs, src/Deserialization/Transaction.purs, src/Metadata/FromMetadata.purs, src/Metadata/Seabug/Share.purs, src/Types/Int.purs
=> Fix unpackMintAssets (FFI)

README.md, doc/ctl-as-dependency.md, doc/getting-started.md, doc/plutus-comparison.md, doc/runtime.md
I added another guide about getting started with actual contract writing for users, and added instructions for upgrading CTL versions
=> Even more docs

CHANGELOG.md, package-lock.json, package.json, server/ctl-server.cabal
Closes #283, bumps some version numbers
=> Small things before v1

examples/Pkh2Pkh.purs
The stake part of address was missing.
=> Fix Pkh2Pkh example

src/Serialization.js, src/Serialization.purs, src/Serialization/AuxiliaryData.purs
=> Remove `setTxAuxiliaryData`

.github/pull_request_template.md
Adds a note to the PR template for updating the changelog with new changes
=> Add a note about the changelog

src/Contract/PlutusData.purs, src/QueryM.purs, src/QueryM/DatumCacheWsp.purs, test/AffInterface.purs
=> Remove `startFetchBlocks`/`cancelFetchBlocks`

CHANGELOG.md, package-lock.json, package.json, src/Types/ScriptLookups.purs
=> Fix `mustBeSignedBy`

Makefile, flake.nix, server/src/Api.hs, server/src/Types.hs
=> Use catchAll in server

CHANGELOG.md, src/Types/ScriptLookups.purs
=> Rename `require` function to not cause problems with webpack

flake.nix, package-lock.json, package.json, spago-packages.nix, spago.dhall, src/Plutip/Server.purs
=> plutip/servers: initial impl startCtlServer

flake.nix
=> Use new node release

README.md
Ecosystem defolkloring effort
Addresses #618
=> Append support channel info to the README

CHANGELOG.md, flake.lock, flake.nix
=> Bump Ogmios

src/Cardano/Types/Transaction.purs, src/Deserialization/Transaction.js, src/Deserialization/Transaction.purs, src/Serialization.js, src/Serialization.purs, test/Fixtures.purs
=> Add collateral return and total collateral (de)serialization + tests

src/Cardano/Types/Transaction.purs, src/Deserialization/Transaction.js, src/Deserialization/Transaction.purs, src/Serialization.js, src/Serialization.purs, test/Fixtures.purs
=> Add reference inputs (de)serialization + tests

src/Types/TxConstraints.purs
=> Add a custom warning for mustPayToPubKey

.gitignore
=> remove node_modules from .gitignore

flake.nix, nix/default.nix, src/Plutip/Server.purs
Also fixes a problem with flags passed to ODC
=> Add `runPlutipTest`

CHANGELOG.md, src/Contract/Monad.purs
=> Add `Alt` and `Plus` instance for `Contract`.

CHANGELOG.md, doc/getting-started.md, examples/Pkh2Pkh.purs, spago.dhall, src/Contract/Transaction.purs, src/QueryM.purs, src/QueryM/DatumCacheWsp.purs
=> Implement `awaitTxConfirmed`

spago-packages.nix
This was forgotten as part of #742
=> Regenerate `spago-packages.nix`

src/Types/Cbor.purs
=> Hotfix `develop`: check for remaining bytearray length correctly

CHANGELOG.md, src/Contract/Wallet.purs, src/Wallet.js, src/Wallet.purs
=> Add isNamiAvailable & isGeroAvailable functions

CHANGELOG.md, examples/AlwaysMints.purs, examples/AlwaysSucceeds.purs, examples/KeyWallet/Pkh2Pkh.purs, examples/KeyWallet/SignMultiple.purs, examples/MintsMultipleTokens.purs, examples/Pkh2Pkh.purs, examples/SignMultiple.purs
=> Add awaitTxConfirmed to all examples

.github/workflows/pages.yml
=> Add Github Pages workflow

README.md, doc/development.md
=> Add notes about github pages

CHANGELOG.md, src/BalanceTx/BalanceTx.purs, src/Contract/Transaction.purs
=> Add balanceTxWithOwnAddress and balanceTxsWithOwnAddress

src/Metadata/ToMetadata.purs
=> Do not use Data.Tuple.Nested./\ (fix bundling issue downstream)

CHANGELOG.md, src/Contract/Test/Plutip.purs, src/Plutip/Server.purs, test/Plutip.purs
=> Enable parallel execution of Contracts in Plutip env

CHANGELOG.md, package-lock.json, package.json, src/Cardano/Types/Transaction.purs, src/Deserialization/Transaction.js, src/Deserialization/Transaction.purs, src/Serialization.js, src/Serialization.purs, src/Serialization/Types.purs, test/Fixtures.purs
=> Update CSL to v11.0.0

src/BalanceTx/BalanceTx.purs
Closes https://github.com/Plutonomicon/cardano-transaction-lib/issues/786
=> Don't set collateral in tx with no phase-2 scripts, Refactor `setCollateral`

packages.dhall, spago-packages.nix
Reverts an issue with a spurious `purescript-toppokki` revision change introduced in #817
=> Fix `purescript-toppokki` revision

CHANGELOG.md, src/Contract/Address.purs
=> Support conversion of Address to Bech32

CHANGELOG.md, examples/AlwaysMints.purs, examples/AlwaysSucceeds.purs, examples/MintsMultipleTokens.purs, src/Hashing.js, src/Hashing.purs, src/Scripts.purs, src/Serialization.purs, src/Serialization/AuxiliaryData.purs, src/Serialization/PlutusScript.js, src/Serialization/PlutusScript.purs, src/Serialization/WitnessSet.js, src/Serialization/WitnessSet.purs, src/Transaction.purs, src/Types/ScriptLookups.purs, test/Hashing.purs
Closes https://github.com/Plutonomicon/cardano-transaction-lib/issues/792
=> Switch to CSL for `PlutusScript` hashing

src/QueryM.purs
Closes https://github.com/Plutonomicon/cardano-transaction-lib/issues/862
=> Make `mkQueryRuntime` use the provided config

CHANGELOG.md, src/BalanceTx/BalanceTx.purs, src/Contract/Address.purs, src/QueryM.purs, src/QueryM/Utxos.purs, test/Plutip.purs
=> Enable getWalletCollateral with KeyWallet

src/NativeScripts.purs, src/Serialization/MinFee.purs, test/NativeScript.purs, test/Plutip.purs, test/Unit.purs
=> Calculate NativeScript maximum required signers number automatically

README.md, doc/faq.md, flake.nix, nix/default.nix, templates/ctl-scaffold/flake.lock, templates/ctl-scaffold/flake.nix, templates/ctl-scaffold/packages.dhall, templates/ctl-scaffold/spago-packages.nix
=> Add packages to shell

doc/development.md, doc/runtime.md
Change-type: patch
Signed-off-by: Giovanni Garufi <giovanni@mlabs.city>
Closes # .
=> Fix a few broken links in docs

flake.lock, flake.nix
This gives us the `PlutusV2` cost models which are required for `babbage`
=> Bump Plutip

CHANGELOG.md, src/Deserialization/Transaction.purs, src/Types/Int.purs
=> Fix bug in from_int in Metadatum deserialization

examples/AlwaysMints.purs, examples/AlwaysSucceeds.purs, examples/ByUrl.purs, examples/Helpers.purs, examples/KeyWallet/MintsAndSendsToken.purs, examples/KeyWallet/Pkh2Pkh.purs, examples/MintsMultipleTokens.purs, examples/Pkh2Pkh.purs, examples/SendsToken.purs, src/BalanceTx/BalanceTx.purs, src/Cardano/Types/Value.purs, test/Plutip.purs
Closes https://github.com/Plutonomicon/cardano-transaction-lib/issues/937
=> BalanceTx: Ensure `changeValue` is positive before calculating min ada

flake.nix
=> Fix the `check`

CHANGELOG.md, examples/AlwaysMints.purs, examples/AlwaysSucceeds.purs, examples/ByUrl.purs, examples/Datums.purs, examples/MintsMultipleTokens.purs, examples/Pkh2Pkh.purs, examples/SignMultiple.purs, examples/Wallet.purs, examples/index.html, nix/runtime.nix, src/Cardano/TextEnvelope.purs, src/Contract/Test/Cip30Mock.purs, src/Contract/TextEnvelope.purs, src/Contract/Wallet.purs, src/Contract/Wallet/KeyFile.purs, src/QueryM.purs, src/Serialization.js, src/Serialization.purs, src/Wallet.js, src/Wallet/Cip30Mock.js, src/Wallet/Cip30Mock.purs, src/Wallet/Key.purs, src/Wallet/KeyFile.purs, test/Integration.purs, test/Plutip.purs
=> Add CIP-30 mock using KeyWallet

doc/faq.md
=> Add a note about motivation for Aeson

package-lock.json, package.json
=> Upgrade CSL to 11.0.5

src/QueryM/Ogmios.purs, src/TxOutput.purs
=> `preprod` support for `babbage`

server/ctl-server.cabal
- x ] All code has been formatted using our config (`make format`)
=> Remove cardano-api dependency from ctl-server

CHANGELOG.md, flake.lock, flake.nix
=> Fix problem with protocolVersion in plutip

CHANGELOG.md, src/Contract/Wallet/Key.purs
=> two keyWallet functions to public api

src/Internal/Types/ScriptLookups.purs
=> check provided datums first

doc/test-plan.md, examples/SatisfiesAnyOf.purs, src/Internal/Types/ScriptLookups.purs, test/Plutip.purs
=> example for mustSatisfyAnyOf and mustHashDatum constraints

.github/workflows/action.yml, .mlc_config.json, CHANGELOG.md, doc/development.md, doc/runtime.md, server/STANDARDS.md
=> Check markdown links on push

.github/workflows/md-link-check.yml
=> deactivate check-new-files-only

CHANGELOG.md, src/Contract/Wallet.purs, src/Internal/QueryM.purs
=> re-export `mkWalletBySpec`

test/Plutip.purs
=> remove only in plutip tests

flake.lock, nix/runtime.nix
=> Update node tag and configuration input

test/Plutip.purs
=> skip "Evaluation with additional UTxOs with native scripts" test

flake.nix
=> Add `file` to shell and formatting check

scripts/whitespace-check.sh
=> format-check with include pattern

nix/runtime.nix
Closes #1190.
Confirmed working with AlwaysSucceeds contract after purging docker containers and re-funding wallet
=> Update block parameters for ODC fetcher post preview restart

doc/side-by-side-ctl-plutus-comparison.md, src/Contract/ScriptLookups.purs, src/Contract/Transaction.purs
=> Update docs to reflect balanceAndSignTx removal

doc/getting-started.md, test/Plutip.purs, test/Plutip/UtxoDistribution.purs
=> remove runPlutipContract from test titles

CHANGELOG.md, doc/test-plan.md, src/Contract/Time.purs, src/Internal/Types/Interval.purs, src/Internal/Types/ScriptLookups.purs, test/BalanceTx/Time.purs, test/Data/Interval.purs, test/Integration.purs, test/Types/Interval.purs, test/Unit.purs
Closes # .
Re-creation of https://github.com/Plutonomicon/cardano-transaction-lib/pull/1125
=> Handle multiple time constraints

flake.lock, flake.nix
Apparently fixes problem with sudden crashes observed by some users.
=> Update ODC in flake.nix

server/nix/default.nix
=> Fix nix develop .#hsDevServer

CHANGELOG.md, doc/getting-started.md, examples/BalanceTxConstraints.purs, src/Contract/BalanceTxConstraints.purs, src/Internal/BalanceTx/BalanceTx.purs, src/Internal/BalanceTx/Constraints.purs, src/Internal/BalanceTx/Error.purs, src/Internal/Types/Aliases.purs
Closes https://github.com/Plutonomicon/cardano-transaction-lib/issues/1206
=> Add `mustSendChangeToAddress` balancer constraint

src/Internal/Plutus/Types/Value.purs
https://app.slack.com/client/T01UN827FQV/C02QXGRGAPK/thread/C02QXGRGAPK-1668658696.949579
https://ci.staging.mlabs.city/log/2filgm8x6azaqidlkm1vfdf7x9i7xrg9-ctl-unit-test.drv
=> Actually use safe CurrencySymbol generation to fix flacky recursion error in Arbitrary Value

CHANGELOG.md, src/Internal/QueryM/Ogmios.purs
=> Add `stakePoolTargetNum` protocol parameter

src/Internal/BalanceTx/BalanceTx.purs
=> Query for UTxOs in parallel

Makefile, README.md, doc/babbage-features.md, doc/ctl-as-dependency.md, doc/development.md, doc/e2e-testing.md, doc/faq.md, doc/getting-started.md, doc/importing-scripts.md, doc/plutip-testing.md, doc/plutus-comparison.md, doc/runtime.md, doc/side-by-side-ctl-plutus-comparison.md, doc/test-plan.md, package-lock.json, package.json
Closes #1283.
No TOC format checking is in this PR.
=> TOC generation with doctoc

src/Internal/BalanceTx/BalanceTx.purs, src/Internal/BalanceTx/CoinSelection.purs, src/Internal/CoinSelection/UtxoIndex.purs, src/Internal/Serialization/Address.purs, src/Internal/Serialization/Hash.purs, src/Internal/Types/Transaction.purs, test/CoinSelection/UtxoIndex.purs, test/Unit.purs
=> Add tests for `UtxoIndex`

src/Contract/Config.purs, src/Internal/Contract/Monad.purs, src/Internal/Contract/QueryBackend.purs, src/Internal/Contract/QueryHandle.purs, src/Internal/Plutip/Server.purs, src/Internal/Test/E2E/Runner.purs
=> Refactor `QueryBackend` and `QueryBackendParams`

examples/ByUrl.purs, examples/Helpers.purs, examples/PaysWithDatum.purs, test/Plutip/Contract.purs
=> Add `PaysWithDatum` example

CHANGELOG.md, src/Internal/Types/TxConstraints.purs
=> Add runtime dependencies to CHANGELOG.md

CHANGELOG.md
=> Fix CHANGELOG english error

test/Integration.purs, test/Plutip/Staking.purs, test/Unit.purs
=> Fix test suites

src/Internal/Plutip/Server.purs, src/Internal/Plutip/Types.purs, src/Internal/Test/E2E/Runner.purs, templates/ctl-scaffold/test/Main.purs, test/Plutip.purs, test/Plutip/Common.purs
=> Update to latest revision

src/Internal/BalanceTx/CoinSelection.purs, src/Internal/Cardano/Types/Value.purs, src/Internal/CoinSelection/UtxoIndex.purs, src/Internal/Types/ByteArray.purs, src/Internal/Types/Transaction.purs, test/CoinSelection/ArbitraryHelpers.purs, test/CoinSelection/RoundRobin.purs, test/CoinSelection/SelectionState.purs, test/CoinSelection/UtxoIndex.purs, test/Unit.purs
Part of https://github.com/Plutonomicon/cardano-transaction-lib/issues/1291
=> Coin selection tests - for runRoundRobinM and SelectionState

src/Internal/Cardano/Types/NativeScript.purs, src/Internal/Cardano/Types/Transaction.purs, src/Internal/QueryM/Ogmios.purs, src/Internal/Types/Interval.purs
=> Apply suggestions to #1329

flake.lock, flake.nix
=> delete haskell related inputs for the flake

CHANGELOG.md
=> Add back unreleased to CHANGELOG.md

nix/default.nix
=> Fix a concurrency problem in E2E test suite in Nix

doc/test-plan.md, src/Internal/Service/Error.purs, test/Plutip/Contract.purs
For https://github.com/Plutonomicon/cardano-transaction-lib/pull/1260
=> Add tests to configurable query backend PR

CHANGELOG.md, package.json, packages.dhall, spago-packages.nix, templates/ctl-scaffold/package.json, templates/ctl-scaffold/packages.dhall, templates/ctl-scaffold/spago-packages.nix
=> Add bignumber.js to package.json, update purescript-bignumber revision

doc/plutip-testing.md, src/Contract/Test/Utils.purs
=> Add docs section for assertions interface, improve docstrings for test utils

test/AffInterface.purs, test/Plutip/Contract.purs
This change improves output of the test suite, making it more descriptive, as requested during the review process.
=> Better organization and titles for plutip tests

E2E-REPORT.md, examples/ByUrl.purs, examples/IncludeDatum.purs, examples/Lose7Ada.purs, examples/PlutusV2/InlineDatum.purs, test/e2e.env
This PR exposes tests for Babbage features to the E2E test suite and adds a report pointing to the on-chain artifacts produced by running them.
=> Expose babbage features tests and put them to the test suite. Prepare a test report

CHANGELOG.md, src/Internal/QueryM/Kupo.purs
=> Retry requests failed due to 503 in Kupo

CHANGELOG.md, src/Internal/Contract/WaitUntilSlot.purs
=> Include more info into `waitUntilSlot` error

src/Internal/Test/UtxoDistribution.purs, test/Plutip/Contract.purs
=> Fix the problem with multiple stake keys in plutip tests

CHANGELOG.md, src/Internal/Contract/WaitUntilSlot.purs, src/Internal/ProcessConstraints.purs, src/Internal/Types/Interval.purs, test/BalanceTx/Time.purs, test/Plutip/Contract.purs, test/Types/Interval.purs
Better implementation of #1467
=> Allow `waitUntilSlot` use with slots very far in the future

src/Internal/Plutip/Server.purs
=> Fix `epochSize` Plutip cluster config option

CHANGELOG.md, README.md, doc/getting-started.md, doc/key-management.md, package-lock.json, package.json, src/Contract/Config.purs, src/Contract/Wallet.purs, src/Contract/Wallet/Key.purs, src/Internal/Serialization/Types.purs, src/Internal/Wallet/Bip32.js, src/Internal/Wallet/Bip32.purs, src/Internal/Wallet/Spec.purs, templates/ctl-scaffold/package-lock.json, templates/ctl-scaffold/package.json, test/Plutip.purs, test/Plutip/Contract/Mnemonics.purs, test/Unit.purs, test/Wallet/Bip32.purs
=> Add support for HD wallets and BIP39 seed phrases

CHANGELOG.md, src/Internal/BalanceTx/BalanceTx.purs, test/Plutip/Contract.purs
=> Fix UTxO set filtering when selecting collateral

flake.lock, flake.nix, templates/ctl-scaffold/flake.lock, templates/ctl-scaffold/flake.nix, templates/ctl-scaffold/packages.dhall, templates/ctl-scaffold/spago-packages.nix
2 related PRs were merged regarding this `blockfrost-backend-ryo` issue https://github.com/blockfrost/blockfrost-backend-ryo/issues/105
Using the latest `blockfrost-backend-ryo` revision fixes the usage for darwin users 👏
=> chore: support for darwin

CHANGELOG.md, test/Wallet/Bip32.purs
=> Fix disabled tests

CHANGELOG.md, examples/ByUrl.purs, examples/ChangeGeneration.purs, src/Internal/BalanceTx/BalanceTx.purs, src/Internal/BalanceTx/Types.purs, src/Internal/Cardano/Types/Transaction.purs, src/Internal/Cardano/Types/Value.purs, src/Internal/Types/PlutusData.purs, src/Internal/Types/TokenName.purs, test/BalanceTx/ChangeGeneration.purs, test/Plutip.purs, test/Plutip/Contract.purs, webpack.config.js
=> Limit number of outputs

src/Internal/BalanceTx/Error.purs
=> Rename error around Ogmios balance

CHANGELOG.md, src/Contract/ScriptLookups.purs, src/Contract/Transaction.purs, src/Contract/UnbalancedTx.purs
=> Remove unnecessary *M functions

CHANGELOG.md, README.md, examples/AdditionalUtxos.purs, examples/ByUrl.purs, examples/ChangeGeneration.purs, packages.dhall, spago-packages.nix, src/Internal/BalanceTx/BalanceTx.purs, src/Internal/BalanceTx/Error.purs, src/Internal/BalanceTx/ExUnitsAndMinFee.purs, src/Internal/BalanceTx/Types.purs, src/Internal/Cardano/Types/Transaction.purs, src/Internal/Cardano/Types/Value.purs, src/Internal/Contract/QueryHandle.purs, src/Internal/QueryM/Ogmios.purs, src/Internal/Service/Blockfrost.purs, src/Internal/Types/PlutusData.purs, src/Internal/Types/TokenName.purs, test/BalanceTx/ChangeGeneration.purs, test/Plutip.purs, test/Plutip/Contract.purs, webpack.config.cjs
=> (Purs15) Provide additional utxos to Blockfrost evaluateTx, Handle AdditionalUtxoOverlap error

CHANGELOG.md, src/Contract/Time.purs
=> New interface for era and time intervals

CHANGELOG.md, doc/keydir.md, src/Contract/Test.purs
=> Expose runContractTestsWithKeyDir from Contract.Test

examples/PlutusV2/ReferenceScripts.purs
=> docs: note on reference script example

CHANGELOG.md, src/Internal/Contract/Hooks.purs, src/Internal/Plutip/Server.purs, src/Internal/Test/E2E/Feedback/Hooks.purs, test/Plutip.purs, test/Plutip/Contract/ClusterParameters.purs
Can be used to access cluster's cardano-node path
=> Add `onClusterStartup` hook

examples/ByUrl.purs
Based on https://github.com/Plutonomicon/cardano-transaction-lib/pull/1596
Additional changes:
* Success message is changed from `Success!` to `[CTL TEST SUCCESS]`
* Added `nami-mainnet` without mocks, to test Cardano Dev Wallet against a Plutip cluster
=> Changes for Cardano Dev Wallet

src/Internal/Testnet/Server.purs
=> Fix `cardano-testnet` process hanging

src/Contract/Test/Testnet.purs, templates/ctl-scaffold/test/Main.purs, test/Testnet.purs, test/Testnet/Logging.purs, test/Testnet/Staking.purs, test/Testnet/UtxoDistribution.purs
=> Expose Testnet API
