spago.dhall
src/Types/JsonWsp.js
src/Types/JsonWsp.purs
src/Types/Transaction.js
src/Types/Transaction.purs

The types here are essentially byte arrays, and JS strings are utf.

 Change some String newtype representations to Uint8Array

---

node-packages.nix
package-lock.json
package.json

Closes #45 
This will add a fork of Sundae's `cardano-serialization-lib` fork to the `node_modules` in our project

Add (fork) fork of CSL to build environment

---

src/Deserialization/UnspentOutput.purs
src/Types/Value.purs

- I think it's safe to make `NonAdaAsset` since `CurrencySymbol` and `TokenName` are safe by construction.
- Therefore, I've added a `Newtype` instance for the `NonAdaAsset`.
- General improvements to some of the helpers, especially `mkSingletonValue` to cover more cases.

Further improvements on Value safety constructors.

---

examples/index.js
examples/nami/BuildTransaction.purs
examples/nami/Pkh2Pkh.purs
src/Types/Transaction.purs

Closes #63. This just builds a `Transaction` through the `QueryM` interface. Running it locally gets as far as balancing
I've changed `examples/index.js` to run this example instead of the older one. We should figure out #100 in order to enable different entry points to be run
There's a placeholder fee of 0 Ada. In the Plutus definition of `Tx`, the fee is a `Value` and this gets set to `mempty` when the transaction first gets built. I'll open an issue about this so we can address it later

Example `Transaction` built with `QueryM`

---

src/BalanceTx.purs
src/Types/Value.purs

- Balancer had issues which meant we weren't able to build a transaction - this is fixed due to a bug in `Value`.
- Balancer now signs at the very end.
- A few fixes in the post balancer to return Ada change.
- Refining `Show` instances in `Value`

Fix `Value` helper and balancer to build transaction

---

src/BalanceTx.purs
src/QueryM.purs

- The pkh2pkh example is still showing ~ +4.83 Ada for the user when trying to submit with their UI collateral option.
- To submit a tx via Nami, it appears to be a requirement that the collateral is not used in the transaction input. Although theoretically, this is allowed: if a tx fails to validate, the collateral is the taken and the inputs (which may include collateral) aren't spent, if the tx validates then the collateral is left alone and the input (which again may include the collateral) is spent. In both scenarios, the collateral is used exactly once. For Nami specifically, if collateral is part of the input, then +5 Ada is automatically added to the transaction for the user despite the transaction balancing internally.
- Therefore, we want `utxosAt` for a Nami wallet to …

Factor Wallet sum type out of `utxosAt`, tx logging and clean up `balanceTx` nesting

---

examples/nami/Pkh2Pkh.purs
src/QueryM.purs
test/AffInterface.purs

Closes #95. Will make it more convenient as we add more websocket connections to `QueryConfig` (e.g. `ogmios-datum-cache`)

Configuration options for WS URLs

---

Makefile
README.md
config.toml
flake.lock
flake.nix
nix/dev-shell.nix

Closes #39 
- The executable can be run from the shell using the same name as the project
- `config.toml` is the configuration file for the service
- Since `ogmios-datum-cache` depends on a running Postgres instance, I added a Makefile target to run it via Docker

Add `ogmios-datum-cache` to shell environment

---

flake.lock
flake.nix
server/nix/default.nix

Closes #168 
This bumps the version of our fork of Ogmios to v5.2.0 (needed to unblock #131 and #167). Haskell.nix has also been bumped out of necessity

Upgrade Ogmios fork to v5.2.0

---

Makefile
flake.nix
server/cardano-browser-tx-server.cabal
server/exe/Main.hs
server/nix/default.nix
server/src/Types.hs

Closes #195. `8081` is still the default, but the server now takes an optional `--port`/`-p` argument
I also took this as an opportunity to make some small improvements to the server and related project setup:
- the server app's name in the `apps` output has been simplified (Makefile also updated)
- a message is logged to the console when starting the server (otherwise it can be difficult to know when the build has finished)

Configurable port for Haskell server

---

src/Serialization.js
src/Serialization.purs

Discovered in the course of fixing #219. Previously, converting the tx body would fail to preserve the script data hash

Fix bug with converting tx body

---

src/ToData.purs

This is a "fix" for the `a /\ b` `ToData` instance. Using the `/\` type constructor causes webpack to freak out:
```
ERROR in ./output/bundle.js 8072:10
Module parse failed: Unterminated string constant (8072:10)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|   exports["toDataBigInt"] = toDataBigInt;
|   exports["toDataUInt"] = toDataUInt;
>   exports["toData/\"] = toData$div$bslash;
|   exports["toDataByteArray"] = toDataByteArray;
| })(PS);
@ ./examples/Seabug/Test.purs 1:0-65
@ ./examples/index.js 4:0-28
```

Fix for tuple instance

---

examples/Seabug/Contract/MarketPlaceBuy.purs
examples/Seabug/Test.purs
src/Contract/Address.purs
src/Contract/ScriptLookups.purs
src/QueryM.purs
src/Types/ScriptLookups.purs
src/Types/UnbalancedTransaction.purs

Closes issue https://github.com/Plutonomicon/cardano-browser-tx/issues/236
- Because the `Address` from our wallet is the full address, using `addressBech32` provides the entire bech32string and not the public key bech32string. Subsequently, the call on `ed25519KeyHashFromBech32` doesn't work because it requires the public key version.
- To resolve I had to go via `StakeCredential` but this means we don't have a `pubKeyHash :: PublicKey -> PubKeyHash` function ATM (since `PublicKey` is a wrapper over the bech32string which is an alias for `String`). I've had to comment out relevant functions and lookups, thankfully I don't believe they affect Seabug.

Fix `ownPaymentPubKeyHash`

---

examples/nami/Pkh2Pkh.purs
examples/nami/Simple.purs
packages.dhall
spago.dhall
src/Contract/Monad.purs
src/Contract/Value.purs
src/Metadata/Seabug.purs
src/QueryM.purs
test/AffInterface.purs

Partially closes #239 as I haven't updated the query endpoint yet with this. This is most of the work to get the metadata (from blockfrost) though, including the HTTP call and JSON decoding for `SeabugMetadata`
Since we are in a massive time crunch, this was hacked together rather quickly and I've made several assumptions, including:
- this will only ever be called on the testnet
- all `TokenName`s are ASCII

Get Seabug metadata

---

Makefile
examples/Seabug/Contract/MarketPlaceBuy.purs
server/src/Api/Handlers.hs
server/src/Types.hs
server/test/Main.hs
src/BalanceTx.purs
src/Contract/Transaction.purs
src/QueryM.purs
src/Wallet.js
src/Wallet.purs

- Borrows from #267 to fix signing
- Signing in balancer has been removed (will fix fee endpoint instead to take number of extra key witnesses as a parameter)
- Node version bumped
- `hashData` has been fixed on both client and server

More Seabug fixes (`hashData`, fixing vkey witnesses)

---

examples/Seabug/Contract/MarketPlaceBuy.purs
src/Contract/ScriptLookups.purs
src/Contract/Transaction.purs
src/ReindexRedeemers.purs
src/Types/ScriptLookups.purs
src/Types/UnbalancedTransaction.purs

- Created from https://github.com/Plutonomicon/cardano-browser-tx/tree/viet/seabug-deployment-fixes
- Made the "temporary" `balanceTx'` the main one (which now returns `UnattachedUnbalancedTx` newtype), because even if we eventually attach datums with CSL, we still need the redeemers (at the very least) to reattach after balancing. I kept this separate from `balanceAndSignTx` (see below).
- ^ So `balancedTx'` and `balanceTx` have swapped names unless it's unclear.
- `balanceAndSignTx`  balances the tx, reindex `Spend` redeemers, attaches datums and redeemers and signs returning the `BalancedSignedTransaction` newtype.
- Removed `submitTransaction :: Transaction -> Contract (Maybe TransactionHash)` from `Contract` API to prevent confusion.
- Finally, the user just needs to submit.
- Any …

Viet/seabug deployment refactor, add `balanceAndSignTx` and related newtypes 

---

src/Contract/Address.purs
src/Contract/Scripts.purs
src/Contract/Transaction.purs
src/Scripts.purs

closes https://github.com/Plutonomicon/cardano-browser-tx/issues/240
- removed `validatorAddress` and `baseValidatorAddress`

remove validatorAddress and validatorBaseAddress

---

src/Metadata/Seabug.purs

Wrong instance was used in `fromData` call.
This makes tests in master pass.

Fix lookupKey

---

flake.lock
flake.nix
nix/default.nix
server/cabal.project
server/nix/default.nix

Closes #327. Depends on #330 
Various project dependencies have been updated:
- nixpkgs, which was pinned to a very old rev previously
- our fork of haskell.nix
- ogmios-datum-cache, which has been updated recently to automatically create the datums DB table
In addition, the nodejs version for the project has been upgraded to `nodejs-14_x`

Bump various dependencies

---

README.md
flake.nix
nix/default.nix

Adds an `entrypoint` argument to `bundlePursProject` (otherwise it might not get copied into the builder)

Add `entrypoint` arg to `bundlePursProject`

---

README.md
flake.nix
nix/default.nix

Symlinking the `node_modules` isn't really necessary and causes more issues than it solves, so that has been removed from the `shellHook`. I also removed the `buildPursProject` package from the flake, since the other package and the `checks` ensure that the entire project compiles (that was my rationale for keeping it previously). This speeds up CI a fair amount

Fix `node_modules`

---

nix/default.nix
webpack.config.js

We need to use the `node_modules` from `process.env.NODE_PATH`, otherwise webpack can't find them

Fix `node_modules` path

---

Makefile
README.md
flake.nix

Closes #333. This adds the ability to configure, generate, and run Arion expressions (a wrapper around docker-compose) to launch all of CTL's required runtime dependencies
For local development and testing, all that is now needed is `nix run .#ctl-runtime` and everything will be launched. I've removed the old `shellHook` and Makefile commands since the `ctl-runtime` app supersedes them and is much easier to maintain
For CTL users, the overlay exposes functions for generating the Arion expressions. I've added a new guide to the readme illustrating how to use this

Arion setup for launching runtime dependencies

---

flake.lock
flake.nix

Currently we only offer support for x86_64. This adds aarch64 support for both Linux and Darwin
I also added `flake-compat` back to the inputs so the compatibility default.nix and shell.nix continue to work

Add ARM support

---

src/Types/Transaction.purs

- TransactionHash is actually a record on Plutus side and uses a zero index ToData/FromData.
- The instance can be found here https://playground.plutus.iohkdev.io/doc/haddock/plutus-ledger-api/html/src/Plutus.V1.Ledger.TxId.html#TxId

fix tx hash todata and fromdata

---

src/BalanceTx.purs
src/Types/ScriptLookups.purs

A small PR to fix a few things:
- Since we're using `Data.Array` instead of `Data.Set`, insertions don't account for duplicates which was a bug. As a result, we were sometimes doubling inputs and causing balancing issues.
- The array is sorted at the very end of balancing to replicate a Set.
- This isn't  a bug but I've optimised tx outputs in script lookups to cons instead of append. The ordering is less important for outputs.
There isn't an outstanding issue for this.

Fix balancer tx input duplicate elements

---

src/Types/ScriptLookups.purs

-  `addDatum` was being called inside `MustPayToScript` of `processConstraints` when it is already being called via `MustIncludeDatum` in `processConstraints` also. Note that the constraint `mustPayToScript` creates two singletons over `MustPayToScript` and `MustIncludeDatum` so we are adding the datum twice. It's possible this doesn't matter if datums are a set anyway.

remove `addDatum` from `MustPayToScript`  of `processConstraints`

---

server/src/Api/Handlers.hs

Closes https://github.com/Plutonomicon/cardano-transaction-lib/issues/380
In particular:
- We can now send value to a script address without requiring a dummy minting policy to mint something - it turns out that a redeemer was required with our current logic. The Alonzo cddl has specific requirements for empty redeemers found here https://github.com/input-output-hk/cardano-ledger/blob/master/eras/alonzo/test-suite/cddl-files/alonzo.cddl#L123
Some `PlutusV2` info can be found here also https://github.com/input-output-hk/cardano-ledger/blob/81a309fa6410d4216724a3eb32e4141da40733e9/eras/alonzo/test-suite/cddl-files/alonzo.cddl#L117

add null redeemers logic to languages in finalizeTx

---

fixtures/schemata/JsonWsp/UtxoQueryResponse.medea
fixtures/test/parsing/JsonWsp/UtxoQueryResponse.json
flake.lock
flake.nix
src/Contract/PlutusData.purs
src/QueryM.purs
src/QueryM/DatumCacheWsp.purs
src/QueryM/JsonWsp.js
src/QueryM/JsonWsp.purs
src/QueryM/UniqueId.js
src/QueryM/UniqueId.purs
src/Types/Transaction.purs
test/AffInterface.purs

Closes #363 
- Update Ogmios to the recent revision
- Fix incorrect handling of Json parse errors for ODC (cancel Aff instead of letting it freeze).
- Remove deleted endpoints (`datumFilter*`)
- (Partially) unify ODC and Ogmios WS code
- Do not rely on response type to match responses with requests for ODC, use reflection instead

Use ogmios-datum-cache reflection

---

src/Contract/Numeric/Rational.purs

`Contract.Numeric.Rational` was re-exporting from `Data.Ratio` instead of our own `Rational` type. This fixes that.

fix `Rational` exports

---

server/ctl-server.cabal
server/src/Api/Handlers.hs
server/test/Main.hs
src/BalanceTx.purs
src/QueryM.purs

Context: https://github.com/Plutonomicon/cardano-transaction-lib/issues/123
The solution was to take into account both script integrity hash and the fee value when estimating fees. 
Now all examples are successfully submitted with accurate fees.

Fix inaccuracies in fee calculation

---

nix/default.nix

We currently allow users to override the default entrypoint using `bundlePursProject`, but if users want to use multiple entrypoints with the same config we need to use the correct flag with webpack

Use `--entry` with bundle derivation

---

.github/workflows/add-to-project.yaml

This will add all newly opened issues to the new CTL project (can only be done via GH Actions)

Automate adding issues to new project

---

nix/default.nix
src/QueryM.purs
src/QueryM/Utxos.purs

Closes #518. Now we can compile with `psa --strict --censor-lib` which will silence the superfluous warnings from libraries and cause building to fail if any compiler warnings are reported (very helpful to catch things like redundant imports, etc...)
- [-] All Purescript imports are explicit, including constructors (n/a)
- [-] **All** existing examples have been run locally against a fully-synced testnet node (n/a)
- [-] The integration and unit tests have been run (`npm run test`) locally (n/a, except I ran the `checks.ctl-unit-test` via Nix to make sure it passes (Hydra is having issues)

Use `psa` for compilation in Nix derivations

---

CHANGELOG.md
flake.lock
flake.nix

Upgraded ODC to `54ad2964af07ea0370bf95c0fed71f60a778ead5` so that datum from datum hash is more stable.

Upgrade ODC for more stable datum gets from datum hash

---

src/QueryM/Utxos.purs

Fix forgotten Nami mention instead of CIP-30

---

CHANGELOG.md
src/QueryM.purs
src/QueryM/JsonWsp.purs
src/QueryM/Ogmios.purs
test/AffInterface.purs

Part of #479 related to Ogmios

Parse `fault` ogmios responses

---

flake.lock
flake.nix

Closes #525, also upgrades the node docker image to the latest release candidate.

Change from vasil-qa to vasil-dev

---

CHANGELOG.md
flake.nix
src/JsWebSocket.js
src/JsWebSocket.purs
src/QueryM.purs

Better handling of first-time WS connections + Fix reconnecting behavior

---

CHANGELOG.md
flake.lock
flake.nix

Closes #583
Waiting for https://github.com/mlabs-haskell/ogmios-datum-cache/pull/87 to be merged to update the revision

Update ODC, Use CLI options instead of config

---

CHANGELOG.md
src/QueryM.purs
src/QueryM/DatumCacheWsp.purs
src/QueryM/Ogmios.purs
test/Utils.purs

This PR improves logging by propagating the errors into the error message that is actually shown to the user.
Also a small refactoring.

Better logging for queryDispatch

---

flake.lock
flake.nix
package.json
spago-packages.nix
spago.dhall
src/Plutip/Server.purs
src/Plutip/Types.purs
test/Main.purs
test/Plutip.purs
test/Unit.purs

Closes # .
In this PR I introduce a `startPostgres` and a `startPlutipServer` function, which enable us to get rid of the need to manually start a `plutip-runtime` and `plutip-server.
One is now able to just run the test without any other steps being required. A developer can just
```
nix develop
spago test -m Plutip.Server
```

get rid of needing docker for launching ctl-runtime-deps

---

CHANGELOG.md
src/BalanceTx.purs
src/Constants/Alonzo.purs
src/Contract/Monad.purs
src/Contract/ProtocolParameters/Alonzo.purs
src/QueryM.purs
src/QueryM/ProtocolParameters.purs

This PR fixes utxo min-ada-value calculation (according to [Min-Ada-Value Calculation in Alonzo](https://github.com/input-output-hk/cardano-ledger/blob/master/doc/explanations/min-utxo-alonzo.rst)) and also closes https://github.com/Plutonomicon/cardano-transaction-lib/issues/612.

Fix utxo min-ada-value calculation

---

examples/AlwaysSucceeds.purs
src/BalanceTx.purs
src/Types/UsedTxOuts.purs

`returnAdaChangeAndFinalizeFees` must be given `allUtxos` for balancing.
Closes # .

Fix locking bug

---

CHANGELOG.md
package-lock.json
package.json
src/BalanceTx.purs
src/TxOutput.purs
src/Types/ScriptLookups.purs
src/Types/UnbalancedTransaction.purs

Closes https://github.com/Plutonomicon/cardano-transaction-lib/issues/647 (backport to `v1.1.0`). Backporting for #650 which should probably be checked before reviewing this.

Change `ScriptOutput` to `TransactionOutput` inside `utxoIndex`  - backport for `master` with `v1.1.0`

---

CHANGELOG.md
package-lock.json
package.json
src/BalanceTx.purs
src/TxOutput.purs
src/Types/ScriptLookups.purs
src/Types/UnbalancedTransaction.purs

Closes # https://github.com/Plutonomicon/cardano-transaction-lib/issues/647. Backporting will be done separately with cherry picks, this should probably be checked and merged before https://github.com/Plutonomicon/cardano-transaction-lib/pull/651 the backporting was created to allow for emergency use of the change.

Change `ScriptOutput` to `TransactionOutput` inside `utxoIndex`

---

CHANGELOG.md
src/Plutus/Types/CurrencySymbol.purs

Provide `From/ToMetadata` instances for `CurrencySymbol` from `Plutus.Types` (reexported by `Contract.Value`).

Add FromMetadata and ToMetadata instances for CurrencySymbol

---

README.md
doc/ctl-as-dependency.md

Closes #671 
Also expands the the section of `doc/ctl-as-dependency.md` that concerns upgrades

Add more details for CTL version bumps, add wallets to readme

---

CHANGELOG.md
test/AffInterface.purs

Based on https://github.com/Plutonomicon/cardano-transaction-lib/pull/675.
Time related tests are failing due to the recent hard fork as we are testing times too far into the future and the `end` field is populated from the era summary. I would expect this will return to null once things stabilise.
I've added lots of comments explaining what happened.

Vasil test fixes - remove times/slots too far in the future

---

fixtures/schemata/JsonWsp/UtxoQueryResponse.medea
fixtures/test/parsing/JsonWsp/UtxoQueryResponse.json
src/QueryM/Ogmios.purs

Fixes parsing of Babbage-era transactions. From changelog for Ogmios v5.5.0: 
> Similarly, Alonzo transaction outputs will now contain a `datumHash` field, carrying the datum hash digest. However, they will also contain a `datum` field with the exact same value for backward compatibility reason. In Babbage however, transaction outputs will carry either `datum` or `datumHash` depending on the case; and `datum` will only contain inline `datums`;

Fix parsing of `OgmiosTxOut`

---

flake.lock
flake.nix

Closes #602.
Closes #608
I also added two flags that make using ODC nicer (`--log-level warn` and `--use-latest`)

Upgrade `ogmios-datum-cache`

---

CHANGELOG.md
src/Cardano/Types/Transaction.purs
src/Deserialization/Transaction.js
src/Deserialization/Transaction.purs
test/Fixtures.purs

Closes #683 
[These](https://github.com/Emurgo/cardano-serialization-lib/pull/460/files) are just deprecations, but I think it's meaningful for us to remove them right now, because we don't really aim at supporting eras except the current one (since we don't handle older eras in Ogmios responses anyway). 
I updated the changelog in this PR in order not to forget (this is technically a breaking change, but it's extremely unlikely we have users of this feature right now).

Vasil features: update protocol params

---

CHANGELOG.md
src/BalanceTx.purs
src/Contract/Transaction.purs

Closes https://github.com/Plutonomicon/cardano-transaction-lib/issues/687

Return error if no utxo is specified for a tx input & Fix transaction inputs locking

---

src/BalanceTx.purs

CI is failing on `develop` due to missing data constructor export

Add missing export

---

packages.dhall

https://github.com/mlabs-haskell/purescript-aeson/pull/9

Update aeson revision

---

src/BalanceTx/BalanceTx.purs
src/Serialization.purs

Fixes being able to run scripts (well, some of the examples now) on the `babbage` branch

Only include the necessary cost models during transaction finalization

---

src/Types/ScriptLookups.purs

Datum was being dropped when using mustPayToScript (babbage)

---

src/QueryM/Utxos.purs

Remove compile-time warning for utxosAt

---

CHANGELOG.md
src/Contract/Wallet.purs
src/Contract/Wallet/KeyFile.purs
src/Serialization.js
src/Serialization.purs
src/Wallet/Key.purs
src/Wallet/KeyFile.purs
test/PrivateKey.purs

Closes # .
Downstream we want to test our CLI with plutip. The cli reads wallets from files so we need a way to get the plain keys out of KeyWallets.
This is the alternative (less breaking thanks) solution suggested by @klntsky in #859

add the keys to the keywallet type

---

flake.nix
templates/ctl-scaffold/README.md
templates/ctl-scaffold/flake.lock
templates/ctl-scaffold/flake.nix
templates/ctl-scaffold/packages.dhall
templates/ctl-scaffold/spago-packages.nix

Fixes an issue introduced in #817. In order to avoid instantiating our own `nixpkgs` (and using our own version of haskell.nix, which can cause painful issues for users), we add `ctl-server` to `overlays.runtime` using the `hsProjectFor` function. If users aren't using haskell.nix themselves, `haskell-nix` will be missing from the package set and `ctl-server` can't be built. This fixes it by checking if that attribute is present and if not applying the overlay
I also fixed the template `welcomeText` so it gets formatted correctly

Make sure `haskell-nix.overlay` has been applied

---

src/Contract/Transaction.purs
src/Plutip/Server.purs
test/Plutip.purs

`MonadError` *only* handles a failure if it arose from an exception, like from `throwError`. It doesn't handle asynchronous cancellation outside of the execution context, eg. when `Aff` is cancelled
Closes #865.

Switch from `withResource`/`try` to `bracket`s where possible

---

test/E2E/Examples/Gero.purs
test/E2E/Examples/Pkh2PkhGero.purs
test/E2E/Helpers.purs

Adjusts the E2E tests to use the new URLs. (Doesn't change the test plan or include Flint yet).

Adjust E2E test to new URLs

---

flake.lock
flake.nix

Part of #906. The new Ogmios version pulls in all of v5.5.4 from upstream

Bump Ogmios version

---

src/BalanceTx/BalanceTx.purs
src/BalanceTx/Error.purs
src/BalanceTx/ExUnitsAndMinFee.purs
src/BalanceTx/Helpers.purs
src/BalanceTx/Types.purs
src/Cardano/Types/Value.purs
src/Serialization/MinFee.purs

Closes https://github.com/Plutonomicon/cardano-transaction-lib/issues/892, Closes https://github.com/Plutonomicon/cardano-transaction-lib/issues/570 (we have a similar problem with CSL fee calculation) 
TODO: description

Rewrite the balancing algorithm so that tx is always pre-balanced before ex units calculation

---

CHANGELOG.md
nix/default.nix

Fix `runPlutipTest` not adding custom `buildInputs` (was #954)

---

nix/runtime.nix

To drop the postgresql state, this should be executed in `psql`:
```
$ psql --host localhost --port 5432 -U ctxlib -d ctxlib
password: ctxlib
```

Use valid firstBlock config for preprod

---

CHANGELOG.md
doc/faq.md
nix/default.nix

It would be nice if our users could access the project including the compiled `output` (to simplify creating custom derivations, etc...), so I've added a `compiled` attribute to what `purescriptProject` returns. I've also added the generated `node_modules` to the return value as well
Not sure if `compiled` is the best name. I'm open to other suggestions. I didn't want to call it `project` (its internal name) because I think most people currently do `project = pkgs.purescriptProject { ... }` and `project.project` looks odd

Expose the compiled project from `purescriptProject`

---

test/Reporter/Console.purs

I thought this might be useful to see what tests take the longest, and to observe changes in durations

Add test duration to output

---

src/Internal/Test/E2E/Feedback/Node.purs
src/Internal/Test/E2E/Runner.purs

This PR simplifies the test suite: we don't need a timeout, since we exit after 10 attempts to connect to the remote contract anyway.

Remove unwanted E2E test suite timeout

---

test/Plutip.purs
test/Plutip/UtxoDistribution.purs

https://github.com/Plutonomicon/cardano-transaction-lib/issues/1232 has hit https://github.com/Plutonomicon/cardano-transaction-lib/pull/1055 twice in the contract tests, which is annoying because all of the tests fail. From my experience, the failures occur after several plutip clusters have been set up, so this change should hopefully avoid this (still not great that we have these failures)
Closes # .

Move distribution tests to after the contract tests, to avoid the cluster failure during contract tests.

---

CHANGELOG.md
examples/AlwaysSucceeds.purs
examples/IncludeDatum.purs
examples/Lose7Ada.purs
examples/PlutusV2/InlineDatum.purs
examples/PlutusV2/ReferenceScripts.purs
test/Plutip/Contract.purs

Throw error when a transaction output can't be found in utxos in Examples

---

src/Internal/Wallet/Cip30Mock.purs
test/Plutip/Contract.purs

Fix CIP30 Mock throwing wrong error when no collateral can be picked

---

flake.lock
flake.nix

Bump plutip to this [pr](https://github.com/mlabs-haskell/plutip/pull/154) that builds on top of the previously used commit.
Hopefully this fixes `ClientHttpError` from #1174.

Plutip-server fixes

---

src/Internal/Deserialization/Keys.js
src/Internal/Serialization.js
src/Internal/Serialization/BigInt.js
src/Internal/Serialization/PlutusData.js
src/Internal/Types/BigNum.js

Closes #1181.
All tests are passing locally. I also ran the reproduction code provided in #875 and confirmed memory access issue no longer occurs.

Remove short-circuiting added for wasm bindgen bug

---

flake.nix

Fix Hercules CI build by restricting CI systems to available agents. Remove unused hydraJobs.

Add ciSystems, remove hydraJobs.

---

src/Internal/Plutip/Server.purs
src/Internal/Plutip/Spawn.purs

cleanup race condition with rmdir sync

---

CHANGELOG.md
examples/ByUrl.purs
examples/SignData.purs
scripts/examples-imports-check.sh
src/Internal/Wallet/Cip30.purs
test/Wallet/Cip30/SignData.purs

Re-play of https://github.com/Plutonomicon/cardano-transaction-lib/pull/1287 without NuFi-related changes
Closes https://github.com/Plutonomicon/cardano-transaction-lib/issues/1286
1. provides `SignData` example, which enables testing of `signData` with browser wallets, using checks developed for our  `KeyWallet` implementation
2. fixes handling of `signData` response **[critical bug fix]**
(List of browser wallets generating valid data signatures according to [CIP-30](https://cips.cardano.org/cips/cip30/#apisigndataaddraddresspayloadbytespromisedatasignature)):
1 test failed (not critical, can be skipped): 
`COSE_Sign1` and `COSE_Key` `kid` headers, if present, must be set to the same value.

Fix `signData` resp handling & Add `SignData` example

---

src/Internal/Test/E2E/Runner.purs

with extraBrowserArgs in runBrowser

---

src/Internal/Wallet/Cip30Mock.purs

https://github.com/Plutonomicon/cardano-transaction-lib/pull/1289 fixed signData, but didn't update the cip30 mock to be correct, causing plutip tests to fail

Output hex in MockCip30s signData

---

CHANGELOG.md
doc/plutus-comparison.md
doc/side-by-side-ctl-plutus-comparison.md
examples/AlwaysMints.purs
examples/AlwaysSucceeds.purs
examples/Helpers.purs
examples/IncludeDatum.purs
examples/KeyWallet/MintsAndSendsToken.purs
examples/KeyWallet/Pkh2Pkh.purs
examples/Lose7Ada.purs
examples/MintsMultipleTokens.purs
examples/MultipleRedeemers.purs
examples/NativeScriptMints.purs
examples/OneShotMinting.purs
examples/Pkh2Pkh.purs
examples/PlutusV2/InlineDatum.purs
examples/PlutusV2/ReferenceInputsAndScripts.purs
examples/PlutusV2/ReferenceScripts.purs
examples/SendsToken.purs
examples/Utxos.purs
src/Contract/Transaction.purs
test/Plutip/Contract.purs

Add `submitTxFromConstraints` instead of `Helpers.buildBalanceSignAndSubmitTx`

---

CHANGELOG.md
src/Internal/Metadata/Cip25/V2.purs
test/Fixtures.purs
test/Metadata/Cip25.purs

Closes #1309.
This is confirmed to fix the issue of Blockfrost not accepting the CIP25 metadata through testing in Seabug using the [`seabug/main`](https://github.com/Plutonomicon/cardano-transaction-lib/tree/seabug/main) branch of CTL. [This](https://preview.cexplorer.io/tx/1e48e0891c3d597b5c8973f7a507bcb7d009a217fa6ed9675d5e13289d869845/metadata#data) is an example of the new CIP25 metadata encoding, and the corresponding response returned from Blockfrost from https://cardano-preview.blockfrost.io/api/v0/assets/1e4409ba69fb38887c23d15a766476384085b66a755530934938abfeabcdef:
```json
{
"asset": "1e4409ba69fb38887c23d15a766476384085b66a755530934938abfeabcdef",
"policy_id": "1e4409ba69fb38887c23d15a766476384085b66a755530934938abfe",
"asset_name": "abcdef",
"fingerprint": …
```

Switch CIP25 metadata keys to use strings

---

Makefile

Also remove the `tmp` exclusion, because this is automatically
excluded as `tmp` is ignored in `.gitignore`

Fix `fd` usage in Makefile to ignore inherited local system configuration

---

nix/test-nixos-configuration.nix

Doesn't really matter, just noticed the port for ctl-server gets forwarded in the nixos config

Remove ctl-server port from test-nixos-configuration.nix

---

CHANGELOG.md
src/Contract/Transaction.purs
src/Internal/BalanceTx/BalanceTx.purs
src/Internal/BalanceTx/CoinSelection.purs
src/Internal/BalanceTx/Error.purs
src/Internal/Test/E2E/Feedback/Node.purs
src/Internal/Types/ScriptLookups.purs
test/Plutip/Contract.purs

Disallow selecting inputs with inline datums/script refs when plutusv1 scripts are used during balancing

---

CHANGELOG.md
src/Internal/Types/OutputDatum.purs

Closes # .
Fix typo causing `OutputDatum` not being able to be decoded

Fix OutputDatum decoding instance

---

CHANGELOG.md
nix/default.nix

This is a relatively tiny change that adds some flexibility to the bundling nix code. When creating a bundle, we currently force the use of webpack, which is totally fine, but we don't make it possible to export the `spago bundle-module` output. This small change adds a flag which allows it to be included in the `dist` folder.

allow keeping bundle-module output in nix bundle

---

CHANGELOG.md
flake.lock
flake.nix

Backporting PR #1390 to v4
Could we release this as 4.0.2?

Backport nix-kupo fix for MacOS

---

CHANGELOG.md
src/Internal/Plutip/Server.purs

Include cluster startup failure detials into `startPlutipCluster` error message

---

nix/default.nix

This fixes the E2E test suite issues appearing due to https://bugs.chromium.org/p/chromium/issues/detail?id=706008#c39

Use a pinned revision of Chromium

---

nix/default.nix

A backport of #1408 for `v4-demo` branch

Use a pinned version of Chromium

---

CHANGELOG.md
src/Internal/Types/ScriptLookups.purs
test/Plutip/Staking.purs

There is a problem with redeemers for stake validators: redeemers were not. in fact, reindexed in the balancer. The index in the redeemer with `Cert` type should point to the corresponding certificate in the array of certificates.

Fix redeemer indexing problem in staking constraints

---

CHANGELOG.md
nix/default.nix

Fixes mlabs-haskell/atrium#108

bundlePursProject: don't crash if output directory exists

---

CHANGELOG.md
examples/SignMultiple.purs
src/Internal/Wallet/Cip30Mock.purs

Boolean inversion bug: we want to filter out collateral UTxOs, not leave only them.

Fix available UTxO set selection in cip30 mock

---

src/Internal/Deserialization/FromBytes.purs
src/Internal/Serialization/ToBytes.purs
test/Deserialization.purs

This PR adds two instances for `FromBytes`: `Vkeywitness` and `Vkeywitnesses`. These instances can be made because CSL exports `.from_bytes` for these types.

add FromBytes for Vkeywitness and Vkeywitnesses

---

CHANGELOG.md
src/Internal/Cardano/Types/Value.purs

Derive `Ring`-like numeric instances for `Coin`

---

nix/runtime.nix

Sets explicitly an optional `project.name` setting.
This doesn't change much, but makes the `buildCtlRuntime` definition compatible with newer versions of `nixpkgs.arion` (see their [CHANGELOG](https://github.com/hercules-ci/arion/blob/main/CHANGELOG.md#breaking)).

Set project.name explicitly in buildCtlRuntime

---

doc/plutip-testing.md

I've checked various `slotLength` values and it doesn't seem to break staking tests (had to un`skip` the `skip`ped ones), while non-default `epochSize` does.

Update plutip test limitations doc

---

doc/importing-scripts.md

Add https://github.com/mlabs-haskell/plutarch-ctl-bridge links to script section in the documentation.

Add `plutarch-ctl-bridge` docs

---

CHANGELOG.md
src/Contract/Wallet.purs
src/Internal/Contract/Sign.purs
src/Internal/Serialization/ToBytes.purs
src/Internal/Wallet.purs
src/Internal/Wallet/Cip30.js
src/Internal/Wallet/Cip30.purs
src/Internal/Wallet/Cip30Mock.purs
src/Internal/Wallet/Spec.purs
test/Plutip/Contract.purs

Re-creation of #1528 from a local branch.

Add support for generic CIP30 wallets by name

---

CHANGELOG.md
src/Contract/Config.purs

Export UseMnemonic and ConnectToGenericCip30 from Contract.Config

---

nix/default.nix

runPursTest node_modules fix

---

CHANGELOG.md
Makefile
src/Internal/Hashing.purs
src/Internal/Types/Redeemer.purs

Looks like a typo was made in the definition long time ago. Seems to not be used, hence not catched

Fix `redeemerHash`

---

flake.lock
flake.nix
nix/runtime.nix
plutip-server/cabal.project
plutip-server/plutip-server.cabal
plutip-server/src/Api.hs

Fyi @klarkc we're figuring out which package set works correctly together.
DONE:
```shell
$ nix -L run .#ctl-runtime
$ cat | websocat ws://localhost:1337/
{"params":{"transaction":{"cbor":"84a400828258207a66e0a95efbc5a8a4f71cedeecb79b989ae01f8d40565e3ec07b1f57c4a12001825825820b69d8dfb613c9c63e180862e67ee9c85c7004391e50467923c4098bec280df6800018283583910793f8c8cffba081b2a56462fc219cc8fe652d6a338b62c7b134876e765ea220670c3dda9e48770296a33332e322fb3ee54c979769c6f042a1a001e84805820923918e403bf43c34b4ef6b48eb2ee04babed17320d8d1b9ff9ad086e86f44ec825839003d7a44531a4d280528adde6c748957f8781bbc1846af3b5772ab03c765ea220670c3dda9e48770296a33332e322fb3ee54c979769c6f042a821a00deb555a1581c363d3944282b3d16b239235a112c0f6e2f1195de5067f61c0dfc0f5fa148546865546f6b656e181a02000f00a2049fd87980ff0580f5f6"},"add …
```

Upgrade cardano-node

---

CHANGELOG.md
src/Internal/Plutip/Server.purs

Unique directory name for Plutip cluster's Kupo instance

---

src/Internal/Contract/QueryHandle.purs
src/Internal/QueryM/Kupo.purs
src/Internal/Service/Blockfrost.purs

Add scripts to `AuxiliaryData` in query layer
